# Generated by Django 4.2.2 on 2025-06-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
