# Generated by Django 4.2.2 on 2025-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_common_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
