# Generated by Django 4.2.2 on 2025-06-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_common_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
