# Generated by Django 4.2.20 on 2025-07-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_gift_gifttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wealthlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('min_coins', models.PositiveIntegerField()),
                ('max_coins', models.PositiveIntegerField()),
                ('badge', models.CharField(choices=[('brass', 'Brass'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], max_length=20)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
    ]
