# Generated by Django 4.2.2 on 2025-07-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0003_userprofile_gifttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GiftTransaction',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
